import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>
            AI Kindergarten Teacher Assistant
          </h1>

          <div className={styles.grid}>
            <a href="/upload" className={styles.card}>
              <h2>Upload Materials &rarr;</h2>
              <p>Upload your curriculum, lesson plans, and reference documents.</p>
            </a>
            <a href="/chat" className={styles.card}>
              <h2>Start Chatting &rarr;</h2>
              <p>Interact with the AI assistant to generate lesson plans and activities.</p>
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
